
/******************************************************************************
*
*   FILE
*   ----
*   SeriesOfMeasurement.c
*
*   History
*   -------
*   2017-10-05   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_lceSeriesOfMeasurement
#define OV_COMPILE_LIBRARY_lceSeriesOfMeasurement
#endif


#include "lceSeriesOfMeasurement.h"
#include "libov/ov_macros.h"
#include "lifeCycleEntry.h"

OV_DLLFNCEXPORT OV_RESULT lceSeriesOfMeasurement_SeriesOfMeasurement_constructor(
	OV_INSTPTR_ov_object 	pobj
) {
    /*    
    *   local variables
    */
	OV_RESULT    result;
	OV_INSTPTR_lceSeriesOfMeasurement_SeriesOfMeasurement pinst = Ov_StaticPtrCast(lceSeriesOfMeasurement_SeriesOfMeasurement, pobj);
    OV_INSTPTR_ov_domain pparentdomain =  NULL;
    OV_INSTPTR_lifeCycleEntry_LifeCycleEntry plceinst = NULL; // Ov_StaticPtrCast(lifeCycleEntry_LifeCycleEntry, pobj);


    /* do what the base class does first */
    result = ov_object_constructor(pobj);
    if(Ov_Fail(result))
         return result;


    /* check if the designated parent node is a LCE. if not, create logfile error*/
    pparentdomain = Ov_GetParent(ov_containment, pinst);
	if (!Ov_CanCastTo(lifeCycleEntry_LifeCycleEntry, pparentdomain)){
		ov_logfile_error("%s: cannot instantiate - Parent have to be from class LifeCycleEntry", pinst->v_identifier);
		return OV_ERR_ALREADYEXISTS;
	}


	/* link pparent to instance of SOM	 */
	plceinst = Ov_StaticPtrCast(lifeCycleEntry_LifeCycleEntry, pparentdomain);
	result = Ov_Link(lifeCycleEntry_attachdatapackage, plceinst, pinst);
	if (Ov_Fail(result)){
		return result;
	}



	/* set data-Variable to NULL as SeriesOfMeasurement is its attached expansion */
	plceinst = Ov_DynamicPtrCast(lifeCycleEntry_LifeCycleEntry, pparentdomain);
	Ov_SetAnyValue(&plceinst->v_Data, NULL);


    return OV_ERR_OK;
}

