
/******************************************************************************
*
*   FILE
*   ----
*   attachdatapackage.c
*
*   History
*   -------
*   2017-10-04   File created
*
*******************************************************************************
*
*   This file is generated by the 'acplt_builder' command
*
******************************************************************************/


#ifndef OV_COMPILE_LIBRARY_lifeCycleEntry
#define OV_COMPILE_LIBRARY_lifeCycleEntry
#endif


#include "lifeCycleEntry.h"
#include "libov/ov_association.h"

#include "libov/ov_macros.h"

OV_IMPL_LINK(lifeCycleEntry_attachdatapackage)
OV_IMPL_UNLINK(lifeCycleEntry_attachdatapackage)
OV_IMPL_GETACCESS(lifeCycleEntry_attachdatapackage)

